### PR TITLE
Updated Add/Edit SAML groups to use ModalForms

### PR DESCRIPTION
**Pull request by patil-pratik-87**

### CODE REVIEW

**Comment by patil-pratik-87** [comment]
Screenshot 2022-03-14 at 4 32 17 PM
Screenshot 2022-03-14 at 4 38 27 PM
Screenshot 2022-03-14 at 4 38 30 PM

**Review by jruddell — CHANGES_REQUESTED** [review]
Dont use `FormFieldCard` for the different sections when inside a modal form. Use the `FormFieldSection` element instead

**Comment by patil-pratik-87** [comment]
> Dont use `FormFieldCard` for the different sections when inside a modal form. Use the `FormFieldSection` element instead

done

**Review by jruddell — APPROVED** [review]

**Review by jruddell — CHANGES_REQUESTED** [review]
Oh can we update the table here to use the new Grid as well?

**Comment by patil-pratik-87** [comment]
> Oh can we update the table here to use the new Grid as well?

I was just targeting the Single Step Wizards but sure, why not?

**Comment by patil-pratik-87** [comment]
> Oh can we update the table here to use the new Grid as well?

@jruddell while migrating to the new grid, found that this was a special case where batch actions are not needed but if not provided the grid doesn't show any selection like checkboxes or radios. Confirmed this with @xantorres and the solution will need a special GridField implementation which might take some time. Should we stick to the ListTable here for now?

**Comment by jruddell** [comment]
> > Oh can we update the table here to use the new Grid as well?
> 
> @jruddell while migrating to the new grid, found that this was a special case where batch actions are not needed but if not provided the grid doesn't show any selection like checkboxes or radios. Confirmed this with @xantorres and the solution will need a special GridField implementation which might take some time. Should we stick to the ListTable here for now?

I understand the issue, and since we haven't gotten to the form component design/architecture, I don't want us to spend extra time trying to make the grid fit inside the existing form system. Can we instead just honor the colors from our theme system in the old ListTable till we get the forms architecture nailed down?

**Comment by patil-pratik-87** [comment]
> > > Oh can we update the table here to use the new Grid as well?
> > 
> > 
> > @jruddell while migrating to the new grid, found that this was a special case where batch actions are not needed but if not provided the grid doesn't show any selection like checkboxes or radios. Confirmed this with @xantorres and the solution will need a special GridField implementation which might take some time. Should we stick to the ListTable here for now?
> 
> I understand the issue, and since we haven't gotten to the form component design/architecture, I don't want us to spend extra time trying to make the grid fit inside the existing form system. Can we instead just honor the colors from our theme system in the old ListTable till we get the forms architecture nailed down?

Yup...I have updated the ListTable with the theme colors and also upgraded the dropdown and input it uses

**Comment by patil-pratik-87** [comment]
Screenshots for colours in different themes -->

Screenshot 2022-03-22 at 10 49 12 AM
Screenshot 2022-03-22 at 10 49 54 AM
Screenshot 2022-03-22 at 10 50 53 AM
Screenshot 2022-03-22 at 10 51 08 AM
Screenshot 2022-03-22 at 10 51 40 AM
Screenshot 2022-03-22 at 10 51 53 AM

**Comment by xantorres** [comment]
Maybe remove the labels in each of the drop downs, it looks a bit too bloated

**Review by xantorres — APPROVED** [review]

**Review by jruddell — APPROVED** [review]

**Pull request merged**
