### PR TITLE
UX-1538/Added ArgoCD and Metal³ plugins

### PR DESCRIPTION
**Pull request by jruddell**
image (48)

image (47)

image (49)
)

### CODE REVIEW

**Review by knnguy — APPROVED** [review]

**Comment by knnguy** [comment]
Are we not doing kebab case for file names anymore?

**Comment by jruddell** [comment]
> Are we not doing kebab case for file names anymore?

We are... which files are you referring to? The only one I can see as a deviation is the `logo.tsx` file name, however, I consider this an edge case where we don't follow the rules. Each plugin should have a consistent form, and a plugin can have the concept of a logo. I want the plugin structure to follow this format so we can improve things with dynamic loading and not need to map variable names into an import statement (as an example).

**Comment by knnguy** [comment]
> > Are we not doing kebab case for file names anymore? Noticed some files with kebab case and the new files with pascal case
> 
> We are... which files are you referring to? The only one I can see as a deviation is the `logo.tsx` file name, however, I consider this an edge case where we don't follow the rules. Each plugin should have a consistent form, and a plugin can have the concept of a logo. I want the plugin structure to follow this format so we can improve things with dynamic loading and not need to map variable names into an import statement (as an example).

I was referring to `InformationalLandingPage.tsx` and `current-plan-card.tsx`

**Comment by jruddell** [comment]
> > > Are we not doing kebab case for file names anymore? Noticed some files with kebab case and the new files with pascal case
> > 
> > 
> > We are... which files are you referring to? The only one I can see as a deviation is the `logo.tsx` file name, however, I consider this an edge case where we don't follow the rules. Each plugin should have a consistent form, and a plugin can have the concept of a logo. I want the plugin structure to follow this format so we can improve things with dynamic loading and not need to map variable names into an import statement (as an example).
> 
> I was referring to `InformationalLandingPage.tsx` and `current-plan-card.tsx`

Thats just a file we haven't refactored, I just did an update inside it. `InformationalLandingPage` is a new file and hence the new naming convention. renaming files should be in its own PR

**Pull request merged**
